# Wandb
wandb:
  project: wos
  resume: allow
  mode: run
  name:
  tags:
  id:

seed: 1

# Setup keops
keops_build_path: ${oc.env:HOME,logs}/.cache/keops/${oc.env:HOSTNAME,unknown}/${now:%Y-%m-%d}/${now:%H-%M-%S}

# Wandb resuming
merge_wandb_resume_cfg: True
restore_ckpt_from_wandb: True

# Hydra
hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${hydra.run.dir}
    subdir: ${hydra.job.override_dirname}
  job:
    env_set: 
      WANDB_START_METHOD: thread
      NUMEXPR_MAX_THREADS: 8
    config:
      override_dirname:
        exclude_keys:
          - launcher
          - ckpt_file
          - wandb.project
          - wandb.id
          - solver.cuda_max_mem_train_mb
        kv_sep: .
        item_sep: "-"
  # launcher:
  #   n_jobs: 5