# invoke the sweep using wandb sweep conf/sweeps/xyz.yaml
program: scripts/main.py
name: nwos_0.5_committor_10d
project: nwos_hp
method: bayes
metric:
  name: relative_error_domain
  goal: minimize
parameters:
  optimizer.lr:
    min: 0.0001
    max: 0.1
  solver.model.hid_dim:
    min: 32
    max: 1024
  solver.model.n_hidden:
    min: 1
    max: 10

command:
  - ${env}
  - python
  - ${program}
  - solver=nwos
  - solver.percentile=0.5
  - solver.n_iters=10000
  - solver.n_batch_domain=10000
  - solver.n_traj=1
  - ${args_no_hyphens}
  - pde=committor_nd
  - pde.n_dim=10

